### ISSUE TITLE
Slack のアカウントが deactivate されたら自動でローテーションから削除して欲しい

### ISSUE THREAD

**Issue by tsub** [mashabow/slack-rota#61]
機能要望です。

[アカウントが deactive (解除)](https://slack.com/intl/ja-jp/help/articles/204475027-%E3%83%A1%E3%83%B3%E3%83%90%E3%83%BC%E3%81%AE%E3%82%A2%E3%82%AB%E3%82%A6%E3%83%B3%E3%83%88%E3%81%AE%E8%A7%A3%E9%99%A4) されても、ローテーションのメンバーには残り続けているため、ローテーションを 1 つ 1 つ編集する必要があって手間がかかります。

<img width="503" alt="貼り付けた画像_2022_10_06_10_03" src="https://user-images.githubusercontent.com/10208211/194191260-9ccc329b-aeca-4725-be3b-25d2c46ccd5b.png">

そのため、アカウントが deactivate されている場合は自動でローテーションから削除してもらえると助かります。

**Comment by mashabow** [comment]
[イベントの一覧](https://api.slack.com/events?filter=Events)を見た感じだと、「deactivate された」というそのもののイベントは無い様子。

その代わりに `user_change` イベントを使えばいいらしい。

> Hi Dave! A 'user_change' event will tell you when an account has been deactivated [https://api.slack.com/events/user_change](https://t.co/hQbt46natA) 💡

https://twitter.com/SlackHQ/status/1009365516367122433

**Comment by mashabow** [comment]
試しに deactivate してみたら、その瞬間に以下のような `user_change` イベントが飛んできた。

```js
{
  "user": {
    "id": "U045LHACU30",
    "team_id": "TD1QU5APK",
    "name": "test_user_1",
    "deleted": true,
    "profile": { /* 中略 */ },
    "is_bot": false,
    "is_app_user": false,
    "updated": 1665387304
  },
  "cache_ts": 1665387304,
  "type": "user_change",
  "event_ts": "1665387304.003800"
}
```

「`user.deleted` の値が `true` だったら deactivated」と判断すればよさそう。

**Comment by tsub** [comment]
新たに Events API (Event Subscription) の導入が必要という少し重めの対応なのに、素早い実装ありがとうございます！！！！ 😄
